[project]
name = "allshowers"
version = "1.0.0"
description = "A point cloud CNF-Transformer to generate any Shower"
readme = "README.md"
authors = [
    {name = "Thorsten Buss", email = "Thorsten.Buss@uni-hamburg.de"},
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "h5py",
    "matplotlib",
    "numpy",
    "pyyaml",
    "torch>=2.8.0,<2.9.0",
    "rangerlite>=1.0.0,<1.1.0",
    "showerdata>=0.6.0,<0.7.0",
    "pot==0.9.5",
]

[dependency-groups]
dev = [
    "ipykernel",
    "ruff",
    "pre_commit",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["allshowers"]

[tool.ruff]
target-version = "py312"
fix = true

[tool.ruff.lint]
extend-select = ["C4", "I", "SIM", "UP"]
